
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim 
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: postgres
        tier: database
    spec:
      containers:
        - image: postgres:latest
          args:
            - "--ignore-db-dir=lost+found" 
          name: postgres
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : postgres-secret
                  key :  password

            - name: POSTGRES_DATABASE 
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName


          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:       
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgres 
      volumes:
        - name: postgres-persistent-storage 
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: postgres  
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:       
    app: postgres
    tier: database
  clusterIP: None 