apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: postgres
  name: postgres-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-test2
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-secret
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: db-config
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
