apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-crud
  template:
    metadata:
      labels:
        app: spring-boot-crud
    spec:
      containers:
        - name: spring-app
          image: spring-boot-crud-k8s.jar:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091