apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: alamin1889/spring-boot-crud-k8s-deploy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8099
          env:
            - name: DB_HOST
              valueFrom : 
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME
              valueFrom :
                secretKeyRef :
                  name : postgres-secret
                  key :  password


---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8099 
      targetPort: 8099 
  type: NodePort 
