apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-postgres
  replicas: 
  template:
    metadata:
      labels:
        app: springboot-k8s-postgres
    spec:
      containers:
        - name: springboot-crud-k8s
          image: alamin1889/test:4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
 
          env:   
            - name: DB_HOST  
              valueFrom :
                configMapKeyRef :
                  name : postgres-secret
                  key : POSTGRES_HOST

            - name: DB_NAME  
              valueFrom :
                configMapKeyRef :
                  name : postgres-secret
                  key :  POSTGRES_DB

            - name: DB_USERNAME 
              valueFrom :
                configMapKeyRef :
                  name : postgres-secret
                  key :  POSTGRES_USER

            - name: DB_PASSWORD 
              valueFrom :
                configMapKeyRef :
                  name : postgres-secret
                  key :  POSTGRES_PASSWORD

---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8091 
      targetPort: 8091 
  type: NodePort 
