apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-postgres
  replicas: 
  template:
    metadata:
      labels:
        app: springboot-k8s-postgres
    spec:
      containers:
        - name: springboot-crud-k8s
          image: alamin1889/test:3.0
          ports:
            - containerPort: 8091
          env:   
            - name: DB_HOST  
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME 
              valueFrom :
                secretKeyRef :
                  name : postgres-secrets
                  key :  username

            - name: DB_PASSWORD 
              valueFrom :
                secretKeyRef :
                  name : postgres-secrets
                  key :  password

---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8091 
      targetPort: 8091 
  type: NodePort 
